### ISSUE TITLE
UX: The "Send Test Notification" button causes settings loss

### ISSUE THREAD

**Issue by MarcSallent** [shopplugins/pushover-for-woocommerce#23]
Hello!

At least during the first setup: if you fill all the fields in the settings page of the plugin and hit "Send Test Notification", this will cause a page reload without saving any setting, causing a loss of all your customizations.

Options to consider
 - It could ask the user if they want to save their settings before sending a test (or they will be lost)
 - It could be greyed out if settings have not been saved

Anyway, great plugin! Thanks!

**Comment by alexmigf** [comment]
I Couldn't replicate this issue, closing for now.
