### ISSUE TITLE
Add Retry and Expire parameters to Emergency priority

### ISSUE THREAD

**Issue by growdev** [shopplugins/pushover-for-woocommerce#24]
Based on [this](https://pushover.net/api#priority) API doc if Emergency priority is used then:

"To send an emergency-priority notification, the priority parameter must be set to 2 and the retry and expire parameters must be supplied."

ref: https://secure.helpscout.net/conversation/958913331/4980?folderId=380165

**Comment by chrishultberg** [comment]
Thanks, that was useful information but I do not have a helpscout account and so hopefully this info will help others, too:

$pushover->setRetry(30);	  //Pushover will resend the notification every 30 seconds until the user accepts.
$pushover->setExpire(3600);   //Pushover will resend the notification for 3600 seconds (1 hour).

Version of 1.0.18 -> Does not support Emergency notifications by default.
It does appear to as the option is in the drop-down list, but it's not fully coded to actually send them with Emergency Priority.

I'll upload a modified, forked version of this in the next few days as this problem caused quite a bit of frustration and I hope to help others alleviate some of the problems that I had.

All-in-all, great open source plugin but it is not supported by Pushover.net, what-so-ever.

**Comment by growdev** [comment]
@chrishultberg 
Thanks. I'll add the retry and expire to the settings and to the `WC_Pushover::send_notification()` method. 

> it is not supported by Pushover.net, what-so-ever.

This is correct. I'm not affiliated with Pushover, but they've reached out before and provide a super useful app.

**Comment by growdev** [comment]
This has been added in 1.0.19.
