### ISSUE TITLE
Additional alerts for affiliate sites using external links

### ISSUE THREAD

**Issue by huemane** [shopplugins/pushover-for-woocommerce#28]
First of all, GREAT PLUGIN! Was waiting for this ;)
Ok, so i run an affiliate store with external product links.
It would be great if, whenever a user either hits the button (add to cart button) which takes them to the external product, I would get an alert.
More difficult perhaps would be when a user clicks a product image which also takes them to the external link?
I'll try and add this myself but if anyone knows how to do this easily, please let me know.
Thanks!

**Comment by huemane** [comment]
Have managed to implement this myself, using jQuery i can get notified of pretty much anything! Right now I've set it up to alert me whenever an item is "added to cart" even for external affiliate products. It's a great feature if you're starting a new affiliate site. When i have time I'll do a pull request if there's interest.
Cheers.

**Comment by growdev** [comment]
@huemane Sorry for the delay in responding!
You're welcome to do a PR and I'll take a look at it. I'm going to close this for now since it's over a year old and will re-open if any PR is created.
