### ISSUE TITLE
HPOS Compatibility

### ISSUE THREAD

**Issue by WiredWonder** [shopplugins/pushover-for-woocommerce#36]
Hey guys, thank you for making a very useful plugin!

Do you have any plans to make this plugin HPOS compatible?

Thanks,
Jason

**Comment by alexmigf** [comment]
Hi @WiredWonder 

Thank you for bringing this to our attention. Since the company was recently acquired, we're still getting up to speed with everything. We'll review the code and push an update as soon as possible.
