### ISSUE TITLE
Problem with WooCommerce 3.0.0

### ISSUE THREAD

**Issue by perfectsenseab** [shopplugins/pushover-for-woocommerce#5]
After upgrading to WooCommerce 3.0.0 the order item name is not appended in the notifications. I think it's due to the fact that get_items is handled differently in 3.0 than in 2.6.

**Comment by lencurrie** [comment]
Yep.. Same.  Love to see an update.

**Comment by f3bruary** [comment]
Can confirm on WC 3.0.2
